# Site settings
title:       Pablo Lerma
email:       me@plerma.com
author:      Pablo Lerma
description: "Pequeño blog sobre desarrollo iOS"
baseurl:     ""
url:         "https://www.plerma.com"

# Google analytics
google_analytics: UA-55026146-2

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Disqus post comments
disqus_shortname: pablolerma

# Social icons
show_social_icons: true
github_username: PabloLerma
stackoverflow_id:
twitter_username: pablo_lerma
google_plus_id:
linkedin_username: pablolerma
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
gems: [jekyll-paginate]
markdown:     kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
permalink:    pretty
paginate:     3
sass:
  compressed: true
